Refactor isFetchingInitial for eslint error
error: prefer-rest arguments

use rest arguments instead of arguments keyword

also do some other clean up

AE-5404 #time 5m